# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_item_label_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='color_label',
            field=models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], default='Best', max_length=10),
            preserve_default=False,
        ),
    ]
