# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200504_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='color_label',
            field=models.CharField(blank=True, choices=[('R', 'red'), ('BLU', 'blue'), ('YEL', 'yellow'), ('BL', 'black'), ('OR', 'orange')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='label_rate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
